{% set version = "1.3.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-xml2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/xml2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/xml2/xml2_{{ version }}.tar.gz
  sha256: e7b03ceeaa63b5341b00b94e055ff8f1f98511aa54ebe0fb6ca8ac4c8c455f61

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-cli                        # [build_platform != target_platform]
    - r-rlang                      # [build_platform != target_platform]
    - gnuconfig                    # [unix]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cli
    - r-rlang >=1.1.0
    - libiconv                     # [win]
    - libxml2
    - liblzma-devel                # [linux]
    - zlib                         # [not osx]
  run:
    - r-base
    - r-cli
    - r-rlang >=1.1.0

test:
  requires:
    - r-testthat
    - r-mockery
  commands:
    - $R -e "library('xml2')"                          # [not win]
    - $R -e "testthat::test_package('xml2')"           # [not win]
    - "\"%R%\" -e \"library('xml2')\""                 # [win]
    - "\"%R%\" -e \"testthat::test_package('xml2')\""  # [win]

about:
  home: https://xml2.r-lib.org/
  dev_url: https://github.com/r-lib/xml2
  license: GPL-2.0-or-later
  summary: Work with XML files using a simple, consistent interface. Built on top of the 'libxml2' C library.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - colinbrislawn
