{% set version = "1.3.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xml2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/xml2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/xml2/xml2_{{ version }}.tar.gz
  sha256: 340bb1a18e643a5008c0b4e92d71c3b0abacb44f1742e3a77d0cb33cb73b3030

build:
  merge_build_host: true  # [win]
  skip: true              # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - gnuconfig                    # [unix]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - {{ native }}libxml2
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - libxml2

test:
  requires:
    - r-testthat
    - r-mockery
  commands:
    - $R -e "library('xml2')"                          # [not win]
    - $R -e "testthat::test_package('xml2')"           # [not win]
    - "\"%R%\" -e \"library('xml2')\""                 # [win]
    - "\"%R%\" -e \"testthat::test_package('xml2')\""  # [win]

about:
  home: https://xml2.r-lib.org/, https://github.com/r-lib/xml2
  license: GPL-2.0-or-later
  summary: Work with XML files using a simple, consistent interface. Built on top of the 'libxml2' C library.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - colinbrislawn
