azure:
  store_build_artifacts: false
bot:
  automerge: true
build_platform:
  # NB: explicitly emulate until we resolve https://github.com/conda-forge/r-xml2-feedstock/issues/24
  linux_aarch64: linux_aarch64
  linux_ppc64le: linux_ppc64le
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: default
  win: azure
test: native_and_emulated
